manifest:
  version: "0.13"

  defaults:
    remote: zephyr

  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: stm32
      url-base: https://github.com/STMicroelectronics
    - name: eclipse-threadx
      url-base: https://github.com/eclipse-threadx

  projects:
    - name: zephyr
      remote: zephyr
      revision: main
      import: true

    # -----------------------------------------------------------------------
    # USBX: STM32 tailored fork mit HAL/DCD Integration fuer alle STM32 Series
    # Tag:   v6.4.0_260116
    # -----------------------------------------------------------------------
    - name: stm32-mw-usbx
      remote: stm32
      revision: 280f6bc
      path: modules/st_usbx
      import: false

    # -----------------------------------------------------------------------
    # ThreadX: Eclipse ThreadX RTOS (benoetigt von USBX als Basis)
    # Tag:   v6.5.0.202601_rel
    # -----------------------------------------------------------------------
    - name: threadx
      remote: eclipse-threadx
      revision: 3726d790
      path: modules/threadx
      import: false

  self:
    path: app
    west-commands: scripts/west-commands.yml